---
apiVersion: v1
kind: Deployment
metadata:
  name: podinfo
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.0.0
        ports:
        - containerPort: 3000
